server:
  port: 8090

spring:
  h2:
    console:
      enabled: true

management: #spring boot actuator
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - metrics
          - end